# Generated by Django 5.2.17 on 2026-09-20 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('events', 'Feasts & Events'), ('menu', 'Menu Updates'), ('rebate', 'Rebates & Leave'), ('rules', 'Hostel Rules')], default='events', max_length=50)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('author', models.CharField(default='Mess Supervisor', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Evening Snacks'), ('Dinner', 'Dinner')], max_length=20)),
                ('start_time', models.CharField(default='07:30 AM', max_length=20)),
                ('end_time', models.CharField(default='09:30 AM', max_length=20)),
                ('is_special', models.BooleanField(default=False)),
                ('special_title', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Special', 'Special'), ('Beverage', 'Beverage'), ('Dessert', 'Dessert')], default='Veg', max_length=20)),
                ('calories', models.IntegerField(default=0)),
                ('protein_g', models.IntegerField(default=0)),
                ('is_chef_special', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mess.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('hostel_block', models.CharField(default='Block B', max_length=50)),
                ('room_number', models.CharField(default='B-304', max_length=50)),
                ('mess_card_id', models.CharField(max_length=50, unique=True)),
                ('diet_preference', models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian'), ('Jain', 'Jain Diet')], default='Veg', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(default='Lunch', max_length=20)),
                ('overall_rating', models.IntegerField(default=5)),
                ('taste_rating', models.IntegerField(default=4)),
                ('hygiene_rating', models.IntegerField(default=5)),
                ('temperature_rating', models.IntegerField(default=4)),
                ('portion_rating', models.IntegerField(default=4)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mess.student')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_info', models.CharField(default='Hostel Resident', max_length=100)),
                ('meal_type', models.CharField(default='Lunch', max_length=20)),
                ('comment', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('supervisor_reply', models.TextField(blank=True, default='')),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mess.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('student_name', models.CharField(default='Rahul Sharma', max_length=100)),
                ('room', models.CharField(default='Room B-304', max_length=50)),
                ('category', models.CharField(choices=[('hygiene', 'Food Hygiene & Cleanliness'), ('quality', 'Poor Cooking / Stale Food'), ('water', 'RO Drinking Water / Dispenser Fault'), ('shortage', 'Food Shortage / Refill Delay'), ('cutlery', 'Unwashed Plates / Dirty Cutlery'), ('timing', 'Mess Timings / Unpunctual Service'), ('staff', 'Mess Staff Conduct'), ('other', 'Other Campus Mess Issue')], max_length=50)),
                ('meal', models.CharField(default='General', max_length=20)),
                ('hall', models.CharField(default='Central Mess Hall 2 (Block B)', max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Normal (24-48h)'), ('medium', 'Medium (Within 24h)'), ('urgent', 'Urgent (Hygiene Hazard)')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mess.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
