# Generated by Django 5.2.17 on 2026-09-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Serving Now', 'Serving Now'), ('Served', 'Served / Closed')], default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15),
        ),
    ]
