# Generated by Django 5.2.17 on 2026-09-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_alter_menu_options_alter_menu_day_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(default='Head Chef', max_length=100)),
                ('experience', models.CharField(default='5 Years', max_length=50)),
                ('speciality', models.CharField(default='South Indian Meals', max_length=150)),
                ('working_days', models.CharField(default='Monday - Sunday', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('photo', models.TextField(blank=True, default='', help_text='Image URL or Base64 encoded image data')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
