# Generated by Django 5.2.17 on 2026-09-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0005_menu_assigned_chef_chefcomplaint_chefrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefcomplaint',
            name='category',
            field=models.CharField(choices=[('Food Quality', 'Food Quality'), ('Taste', 'Taste'), ('Hygiene', 'Hygiene'), ('Quantity', 'Quantity'), ('Behaviour', 'Behaviour'), ('Other', 'Other')], default='Food Quality', max_length=50),
        ),
    ]
