# Generated by Django 5.2.17 on 2026-09-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0006_alter_chefcomplaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefcomplaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
