# Generated by Django 5.2.17 on 2026-09-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0008_chefcomplaint_accepted_at_chefcomplaint_accepted_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
