# Generated by Django 5.2.17 on 2026-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0009_delete_announcement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menu',
            name='unique_weekly_meal_per_day',
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('date', 'meal_type'), name='unique_menu_per_date_meal'),
        ),
    ]
