# Generated by Django 5.2.17 on 2026-09-24 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0010_remove_menu_unique_weekly_meal_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], max_length=20)),
                ('swipe_time', models.CharField(default='08:20 AM', help_text='e.g. 08:20 AM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='mess.student')),
            ],
            options={
                'ordering': ['date', 'meal_type'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date', 'meal_type'), name='unique_attendance_per_student_date_meal')],
            },
        ),
    ]
